export const GET_ALL_POSTS = "GET_ALL_POSTS"
export const GET_ALL_SPECIALITIES = "GET_ALL_SPECIALITIES"
export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const GET_ALL_TEACHERS = "GET_ALL_TEACHERS"

export const GET_POST = "GET_POST"
export const GET_SPECIALITY = "GET_SPECIALITY"
export const GET_COURSE = "GET_COURSE"
export const GET_FRAGMENT = "GET_FRAGMENT"
